import mongoose from 'mongoose';

const scrapeSchema = new mongoose.Schema({
    "_id": {
        "$oid": "ObjectId" // The unique identifier for each document, automatically generated by MongoDB
    },
    "title": "String", // The title of the movie or TV series
    "url": "String", // The URL of the content
    "image": "String", // The URL of the content's image
    "slug": "String", // A unique slug for the content
    "content": "String"
}
);

export const Contents = mongoose.models.Contents || mongoose.model('Contents', scrapeSchema);
