import mongoose from 'mongoose';

const scrapeSchema = new mongoose.Schema({
    "_id": {
        "$oid": "ObjectId" // The unique identifier for each document, automatically generated by MongoDB
    },
    "title": "String", // The title of the movie or TV series
    "url": "String", // The URL of the content
    "image": "String", // The URL of the content's image
    "slug": "String", // A unique slug for the content
    "content": "String",
    "filmHeaders": ["String"], // An array of strings for film headers
    "filmH3AnchorTags": ["String"], // An array of strings for H3 anchor tags
    "filmH4AnchorTags": ["String"], // An array of strings for H4 anchor tags
    "filmPAnchorTags": ["String"], // An array of strings for paragraph anchor tags
    "filmTrailers": ["String"], // An array of strings for film trailers (e.g., YouTube embed codes)
    "filmStorylines": ["String"], // An array of strings for film storylines or descriptions
    "filmReviews": ["String"] // An array of strings for film reviews or comments
}
);

export const Contents = mongoose.models.Contents || mongoose.model('Contents', scrapeSchema);
